apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector: 
    app: hello
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 4    
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: dtyuev/uwsgi-nginx-hello:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80  
